name: Push-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - server: 1
            HOST_SECRET: HOST_DNS
            SSH_SECRET: EC2_SSH_KEY
            PROFILE: server1
          - server: 2
            HOST_SECRET: HOST2_DNS
            SSH_SECRET: EC2_SSH_KEY2
            PROFILE: server2
          - server: 3
            HOST_SECRET: HOST3_DNS
            SSH_SECRET: EC2_SSH_KEY3
            PROFILE: server3

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server ${{ matrix.server }}
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets[matrix.SSH_SECRET] }}
          REMOTE_HOST: ${{ secrets[matrix.HOST_SECRET] }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          
      - name: Executing remote SSH commands on Server ${{ matrix.server }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[matrix.HOST_SECRET] }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets[matrix.SSH_SECRET] }}
          script: |
            sudo yum -y update
            sudo yum -y install sqlite-devel
            sudo yum -y install java-17-amazon-corretto
            cd ${{ secrets.TARGET_DIR }}
            chmod +x run-app.sh
            ./run-app.sh ${{ matrix.PROFILE }}
